// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package routes

import (
	"customer-api/model"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCustomerService creates a new instance of MockCustomerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCustomerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCustomerService {
	mock := &MockCustomerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCustomerService is an autogenerated mock type for the CustomerService type
type MockCustomerService struct {
	mock.Mock
}

type MockCustomerService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCustomerService) EXPECT() *MockCustomerService_Expecter {
	return &MockCustomerService_Expecter{mock: &_m.Mock}
}

// AddCustomer provides a mock function for the type MockCustomerService
func (_mock *MockCustomerService) AddCustomer(customer model.Customer) (int64, error) {
	ret := _mock.Called(customer)

	if len(ret) == 0 {
		panic("no return value specified for AddCustomer")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(model.Customer) (int64, error)); ok {
		return returnFunc(customer)
	}
	if returnFunc, ok := ret.Get(0).(func(model.Customer) int64); ok {
		r0 = returnFunc(customer)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(model.Customer) error); ok {
		r1 = returnFunc(customer)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCustomerService_AddCustomer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddCustomer'
type MockCustomerService_AddCustomer_Call struct {
	*mock.Call
}

// AddCustomer is a helper method to define mock.On call
//   - customer model.Customer
func (_e *MockCustomerService_Expecter) AddCustomer(customer interface{}) *MockCustomerService_AddCustomer_Call {
	return &MockCustomerService_AddCustomer_Call{Call: _e.mock.On("AddCustomer", customer)}
}

func (_c *MockCustomerService_AddCustomer_Call) Run(run func(customer model.Customer)) *MockCustomerService_AddCustomer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 model.Customer
		if args[0] != nil {
			arg0 = args[0].(model.Customer)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCustomerService_AddCustomer_Call) Return(n int64, err error) *MockCustomerService_AddCustomer_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockCustomerService_AddCustomer_Call) RunAndReturn(run func(customer model.Customer) (int64, error)) *MockCustomerService_AddCustomer_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllCustomer provides a mock function for the type MockCustomerService
func (_mock *MockCustomerService) GetAllCustomer() ([]model.Customer, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllCustomer")
	}

	var r0 []model.Customer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]model.Customer, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []model.Customer); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Customer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCustomerService_GetAllCustomer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllCustomer'
type MockCustomerService_GetAllCustomer_Call struct {
	*mock.Call
}

// GetAllCustomer is a helper method to define mock.On call
func (_e *MockCustomerService_Expecter) GetAllCustomer() *MockCustomerService_GetAllCustomer_Call {
	return &MockCustomerService_GetAllCustomer_Call{Call: _e.mock.On("GetAllCustomer")}
}

func (_c *MockCustomerService_GetAllCustomer_Call) Run(run func()) *MockCustomerService_GetAllCustomer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCustomerService_GetAllCustomer_Call) Return(customers []model.Customer, err error) *MockCustomerService_GetAllCustomer_Call {
	_c.Call.Return(customers, err)
	return _c
}

func (_c *MockCustomerService_GetAllCustomer_Call) RunAndReturn(run func() ([]model.Customer, error)) *MockCustomerService_GetAllCustomer_Call {
	_c.Call.Return(run)
	return _c
}

// GetCustomer provides a mock function for the type MockCustomerService
func (_mock *MockCustomerService) GetCustomer(id string) (*model.Customer, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetCustomer")
	}

	var r0 *model.Customer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*model.Customer, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *model.Customer); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Customer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCustomerService_GetCustomer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCustomer'
type MockCustomerService_GetCustomer_Call struct {
	*mock.Call
}

// GetCustomer is a helper method to define mock.On call
//   - id string
func (_e *MockCustomerService_Expecter) GetCustomer(id interface{}) *MockCustomerService_GetCustomer_Call {
	return &MockCustomerService_GetCustomer_Call{Call: _e.mock.On("GetCustomer", id)}
}

func (_c *MockCustomerService_GetCustomer_Call) Run(run func(id string)) *MockCustomerService_GetCustomer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCustomerService_GetCustomer_Call) Return(customer *model.Customer, err error) *MockCustomerService_GetCustomer_Call {
	_c.Call.Return(customer, err)
	return _c
}

func (_c *MockCustomerService_GetCustomer_Call) RunAndReturn(run func(id string) (*model.Customer, error)) *MockCustomerService_GetCustomer_Call {
	_c.Call.Return(run)
	return _c
}
